# Play with topic modeling

In [1]:
import sys
from pathlib import Path
sys.path.append(Path.cwd())
from topic_modeling.pipeline import TopicModelingPipeline

/Users/anapreciado/Desktop/github_repos/dataccion-agent/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [31]:
pipeline = TopicModelingPipeline(
    min_cluster_size=6,
)

In [32]:
results = pipeline.run()

2026-03-29 15:36:32,300 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-03-29 15:36:33,240 - BERTopic - Dimensionality - Completed ✓
2026-03-29 15:36:33,240 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-03-29 15:36:33,255 - BERTopic - Cluster - Completed ✓
2026-03-29 15:36:33,255 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-03-29 15:36:33,289 - BERTopic - Representation - Completed ✓

In [33]:
# Lets now inspect individual topics

model = results.model

# All topics as a DataFrame
model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,0,533,0_women_labor_gender_work,"[women, labor, gender, work, region, men, part...",[24\nEVOLUTION OF FEMALE LABOR FORCE PARTICIPA...
1,1,219,1_women_companies_employees_workplace,"[women, companies, employees, workplace, manag...",[35 | WOMEN IN THE WORKPLACE: WOMEN'S EXPERI...
2,2,59,2_gender_america_bank_washington,"[gender, america, bank, washington, developmen...",[91\nREFERENCES\nCLOSING \nGENDER GAPS \nIN TH...
3,3,22,3_woman_manager_people_manager women,"[woman, manager, people, manager women, workpl...",[IN THEIR WORDS: THE EXPERIENCES OF YOUNGER WO...
4,4,8,4_does_leave_law_benefits,"[does, leave, law, benefits, pension, paid, ma...",[sexual harassment in employment.\n Ì Women ca...

In [39]:
model.get_topic_info()["Representation"][1]

['women',
 'companies',
 'employees',
 'workplace',
 'managers',
 'color',
 'women color',
 'men',
 'diversity',
 'women workplace']

In [27]:
# Attach the raw text to the assignments DataFrame
doc_topics = results.document_topics.copy()
doc_topics["text"] = results.corpus.texts

In [15]:
doc_topics.groupby(["topic"])[["probability"]].mean()

       probability
topic
0         0.860066
1         0.871559
2         0.807905
3         0.844718

In [16]:
for idx, x in enumerate(list(doc_topics[doc_topics["topic"]==0]["text"])):
    print("===="*8) 
    print(f"{idx}")
    print("===="*8 )
    print(x)

================================
0
================================
Companies now oﬀer more signiﬁcant employee
work-life beneﬁts
Today, almost all companies provide critical support for employees who are parents, caregivers, or
struggling with health challenges—and these beneﬁts are linked to higher rates of happiness and
better employee retention.39 In addition, beneﬁts like these are especially helpful to women, who are
more likely to have caregiving responsibilities.40
Companies have signiﬁcantly increased beneﬁts for parents …41
% of companies oﬀering the following forms of leave42
… And for employees navigating illness and loss
% of companies oﬀering the following forms of leave in 2024
Extended maternity
leave beyond what’s
required by law
48%
54%
62% 60%
Extended paternity
leave beyond what’s
required by law
Paid maternity leave
70%
================================
1
================================
leave beyond what’s
required by law
48%
54%
62% 60%
Extended paternity
leave beyond what’s
required by law
Paid maternity leave
70%
86%78%
92%
Paid paternity leave
100%
0%
In 2024, 96% of
companies oﬀered
maternity leave
and 93% oﬀered
paternity leave.
Other supports for parents have improved. Half of companies
now provide emergency backup childcare services—up from
1 in 3 in 2016—and 8 in 10 organizations now oﬀer beneﬁts for
fertility treatments and adoption or surrogacy.43
Paid sick leave beyond
what’s required by law
Paid family leave beyond
what’s required by law
Paid bereavement leave
84%
59%
96%
100%50% In 2024, half of companies
oﬀered support for caregivers
of sick or elderly adults—and 1 in
3 oﬀered compassionate leave,
up from 1 in 4 the previous year.44
================================
2
================================
oﬀered support for caregivers
of sick or elderly adults—and 1 in
3 oﬀered compassionate leave,
up from 1 in 4 the previous year.44
25  |  WOMEN IN THE WORKPLACE: COMPANY PRACTICES
2020
2022
2018
2015
2021
2016
2017
2019
2023
2024
20202018
2022 2024
2015 2017 2018 2021
2024
================================
3
================================
Companies have signiﬁcantly expanded workplace ﬂexibility
Mostly in response to the pandemic, companies have dramatically increased their remote/hybrid work
options. Almost 8 in 10 employees say ﬂexibility has improved over the last decade, and employees
consistently point to greater productivity and reduced burnout as primary beneﬁts.45 And ﬂexibility is
especially important to women, who report having more focused time to get their work done when
working remotely.46
Companies oﬀer more opportunities for remote/hybrid work ...
% of companies oﬀering remote/hybrid work options47
… And most employees think ﬂexibility has improved
% of employees saying how opportunities to work ﬂexibly have changed in the last 10 years48
76% 75%
92% Remote/hybrid
work options
100%
0%
96%
================================
4
================================
% of employees saying how opportunities to work ﬂexibly have changed in the last 10 years48
76% 75%
92% Remote/hybrid
work options
100%
0%
96%
20182015 2021 2024
Gotten better Stayed the same Gotten worse
MEN
WOMEN
5%
5%11%
10%82%
83%
There are signs that companies are beginning to scale back on ﬂexibility.
One in 3 employees saw a decline in ﬂexibility in 2024; this may be due to
companies updating their policies or because remote work feels less
accessible compared to the peak of the pandemic.
26  |  WOMEN IN THE WORKPLACE: COMPANY PRACTICES
2024
================================
5
================================
Women continue to shoulder more housework
Women still do far more housework than men. Today, roughly 4 in 10 women with partners say
they are responsible for most or all of the housework—the same as in 2016. In contrast, over the
same period of time, far more men report they share housework equally with their partner. These
diverging perceptions are concerning, as they point to a growing gap in how women and men
see their contributions at home. On top of this, younger women report doing the same amount
of housework as older women, and this also signals a lack of progress.
A CLOSER LOOK
Women with partners are still more likely to do most of the housework
% of distribution of household responsibilities reported by partnered women and men
MEN WOMEN MEN WOMEN
35%8%
61%
58%
7%
32%
================================
6
================================
% of distribution of household responsibilities reported by partnered women and men
MEN WOMEN MEN WOMEN
35%8%
61%
58%
7%
32%
They are responsible for
most or all of the work
They share responsibilities
equally with a partner or
family member
Someone else is
responsible for most or
all of the work
39%
75%
57%
3%
14%
11%
Across generations, over a third of women
with partners do most or all of the housework
% of partnered women under 30 and partnered
women 50 and over who report taking on most
or all of the household responsibilities64

YOUNGER WOMEN 38%
OLDER WOMEN 37%
Regardless of seniority at work, women continue to do more at home.  Senior-level women with partners are
================================
7
================================
YOUNGER WOMEN 38%
OLDER WOMEN 37%
Regardless of seniority at work, women continue to do more at home.  Senior-level women with partners are
over 4x more likely than men in the same situation to do more housework: 35% say that they take on most or all
of the household responsibilities, compared to just 8% of men.
39  |  WOMEN IN THE WORKPLACE: WOMEN'S EXPERIENCES
2020
2022
2018
2015
2021
2016
2017
2019
2023
2024
20202018
2022 2024
2024
2016 2024
================================
8
================================
the study. Current representation at the executive level (C-suite + SVP) was projected forward using simulations that incorporated hiring,
promotion, and attrition rates until parity thresholds were reached. See Methodology for complete details on parity projection analysis.
19.Except where otherwise noted, “ﬂexible work” or “ﬂexibility” refers to remote or hybrid work, as well as ﬂexible work options such as the
ability to set your own hours.
20.Shelley J. Correll, “Reducing Gender Biases in Modern Workplaces: A Small Wins Approach to Organizational Change,” Gender & Society
31, no. 6 (December 2017), https://journals.sagepub.com/doi/abs/10.1177/0891243217738518?journalCode=gasa; Lori Nishiura Mackenzie,
================================
9
================================
is restricted to employees in the workforce for at least 10 years.
38.Data compare women of color, men of color, white women, and white men.
39.Eileen Appelbaum and Ruth Milkman, “Leaves That Pay: Employer and Worker Experiences with Paid Family Leave in California,” Center
for Economic and Policy Research, 2011, http://cepr.net/documents/publications/paid-family-leave-1-2011.pdf.
40.Richard Fry, Carolina Aragão, Kiley Hurst, and Kim Parker, “In a Growing Share of U.S. Marriages, Husbands and Wives Earn About the
Same,” Pew Research Center, 2023, https://www.pewresearch.org/social-trends/2023/04/13/in-a-growing-share-of-u-s-marriages
-husbands-and-wives-earn-about-the-same/#:~:text=Among%2 0parents%20in%20marriages%20where,per%20week%20on%20paid%
================================
10
================================
-husbands-and-wives-earn-about-the-same/#:~:text=Among%2 0parents%20in%20marriages%20where,per%20week%20on%20paid%
20work; Organization for Economic Cooperation and Development, “Employment: Time spent in paid and unpaid work, by sex,” 2023,
https://stats.oecd.org/index.aspx?queryid=54757#.
41.The distance between time markers on the horizontal axis does not scale to match the timeline.
42.The wording of survey questions varied across years. Data points in the line chart are connected where the question language
remained consistent or diﬀered only slightly. Full question: In 2015, “Which of the following ﬂexible work programs does your
organization oﬀer?” Options included “Extended maternity leave” and “Extended paternity leave.” In 2017, “Which of the following
================================
11
================================
organization oﬀer?” Options included “Extended maternity leave” and “Extended paternity leave.” In 2017, “Which of the following
work/life practices or policies does your company oﬀer to its employees?” Options included “Extended maternity leave (deﬁned as leave
that exceeds legal requirements)” and “Extended paternity leave (deﬁned as leave that exceeds legal requirements).” In 2018, “What
programs does your company oﬀer related to work/life balance?” Options included “Paid maternity leave” and “Paid paternity leave.” In
2021, “Which of the following does your company provide for parents?” Options included “Paid maternity leave” and “Paid paternity
leave.” In 2024, “Which of the following does your organization oﬀer to all employees?” Options included “Maternity leave” and
================================
12
================================
leave.” In 2024, “Which of the following does your organization oﬀer to all employees?” Options included “Maternity leave” and
“Paternity leave.”
43.Unpublished data. In 2016, “Which of the following work/life practices or policies does your company currently oﬀer?” Respondents
selected “Emergency backup childcare services”; results, 31 percent. In 2022, “Which of the following types of support does your
organization provide to help parents?” Respondents selected “Support for adoption, surrogacy, and/or IVF/fertility treatment (e.g., paid
leave beyond what may be required by law or assistance with fees)”; results, 80 percent; “Emergency backup childcare services
================================
13
================================
leave beyond what may be required by law or assistance with fees)”; results, 80 percent; “Emergency backup childcare services
(in-home or out-of home)”; results 50 percent. In 2024, “Which of the following does your organization oﬀer to all employees?”
Respondents selected “Support for adoption and/or surrogacy,” “Support for IVF/fertility treatment”; results, companies oﬀering support
for adoption and/or surrogacy or support for IVF/fertility treatment, 87 percent.
64  |  WOMEN IN THE WORKPLACE: ENDNOTES
================================
14
================================
Endnotes
44.Support for caregivers of sick or elderly adults constitutes a beneﬁt beyond paid leave (e.g., caregiver reimbursements).
45.Laura Wheeler Poms, Lila C. Fleming, and Kathryn H. Jacobsen, “Work-Family Conﬂict, Stress, Physical and Mental Health: A Model for
Understanding Barriers to and Opportunities for Women’s Well-Being at Home and in the Workplace,” Social Determinants of Health,
virtual issue (2016): 444–57, https://onlinelibrary.wiley.com/doi/abs/10.1002/wmh3.211@10.1111/(ISSN)1948-4682.social-determinants-of
-health; Sari Mansour, “Work-family conﬂict/Family-work conﬂict, job stress, burnout and intention to leave in the hotel industry in Quebec
================================
15
================================
-health; Sari Mansour, “Work-family conﬂict/Family-work conﬂict, job stress, burnout and intention to leave in the hotel industry in Quebec
(Canada): Moderating role of need for family friendly practices as ‘resource passageways,’” The International Journal of Human Resource
Management 29, no. 16 (2018): 2399–430, https://www.tandfonline.com/doi/abs/10.1080/09585192.2016.1239216.
46.LeanIn.Org and McKinsey & Company, Women in the Workplace 2023.
47.Full question: In 2024, “Which of the following does your organization oﬀer to all employees?” Respondents selected: “Remote/hybrid
work options.” In 2021, “How much ﬂexibility do employees currently have to … Work remotely.” Respondents selected from an aggregate
================================
16
================================
work options.” In 2021, “How much ﬂexibility do employees currently have to … Work remotely.” Respondents selected from an aggregate
of “A little bit,” “A fair amount,” “A lot,” and “Almost total.” In 2018, “What programs does your company oﬀer related to work/life balance?”
Respondents selected: “Telecommuting: Opportunity to work from home at least one day per week.” In 2015, companies oﬀered:
logistical ﬂexibility (e.g., telecommuting, no meetings after 5pm). In some circumstances, remote/hybrid options were oﬀered by
companies, but not to all employees.
48.Total percentage of employees saying how opportunities to work ﬂexibly have changed in the last 10 years does not include respondents
================================
17
================================
What Is the Labor Market like for
Women in Latin America and the
Caribbean?
Veronica Frisancho
Monserrat Bustelo
Mariana Viollaz
================================
18
================================
What ls the Labor Market like for Women in Latin
America and the Caribbean?
Veronica Frisancho
Monserrat Bustelo
Mariana Viollaz
December 2023
_,IDB
Inter-American
Development Bank
================================
19
================================
the UNCITRAL rules. The use of the I DB's name for any purpose other than for attribution, and the use of I DB's logo shall be
subject to a separate written license agreement between the IDB and the user and is not authorized as part of this CC-IGO license.
Note that link provided above includes additional terms and conditions of the license.
The opinions expressed in this publication are those of the authors and do not necessarily reflect the views of the Inter-American
Development Bank, its Board of Directors, or the countries they represent.
https://gdlab.iadb.org/
gdlab@iadb.org
================================
20
================================
1
Women face significant gaps and have a low labor force participation rate. The labor force participa-
tion of women in Latin America and the Caribbean is low, and the region’s gender gap is one of the
widest in the world. Although important progress has been made over the last 50 years (with women’s
participation rate going from around 20% in the 1960s to more than 60% toward the beginning of the
2010s), the pace of growth slowed down in the early 2000s, and the rate remains much lower than the
participation rate for men, which stands at over 80%.
Women’s participation levels are extremely heterogeneous: More does not mean better. Even among
women, the outlook is far from homogenous, and there are still large diﬀerences between countries. Mex-
================================
21
================================
women, the outlook is far from homogenous, and there are still large diﬀerences between countries. Mex-
ico and Peru are great examples of this. Although both countries have very similar characteristics in terms
of many of the aspects related to women’s participation in the labor force, in Mexico, six out of 10 women
participate in the labor market, while in Peru, the ﬁgure stands at eight. Part of the diﬀerence is explained
by the quality of employment, especially in rural areas; Peruvian women are more likely to be employed
in low-quality jobs such as self-employment, unpaid, informal, or part-time jobs. The situations observed
in Peru and Mexico appear to a greater or lesser extent in other countries in Latin America. Thus, both
job quantity and job quality are relevant.
================================
22
================================
in Peru and Mexico appear to a greater or lesser extent in other countries in Latin America. Thus, both
job quantity and job quality are relevant.
What is the labor market like for
women in Latin America and the
Caribbean?
POLICY BRIEF #2
================================
23
================================
2
 What factors determine women’s
 participation in the labor market?
There are multiple factors underpinning women’s
decision to participate in the labor market. What
does the available evidence tell us?
Gender norms tend to be relevant. One key fac-
tor has to do with the cultural expectations sur -
rounding the role of women as the main caregiv-
ers. Latin American and Caribbean women spend
twice as many hours as men  doing domestic
labor and unpaid care work (38 compared to 16
hours per week, respectively). This gap widens
in homes with children younger than ﬁve, where
the diﬀerence of unpaid work between women
and men reaches 33 hours per week. Maternity
penalizes women—the gender gap in labor force
participation widens to 40 percentage points
================================
24
================================
and men reaches 33 hours per week. Maternity
penalizes women—the gender gap in labor force
participation widens to 40 percentage points
when comparing men and women who have chil-
dren under the age of ﬁve. In contrast, the gap is
smaller (24 percentage points) between men and
women with children older than 18. The evidence
suggests that interventions facilitating access to
daycare can increase women’s labor force partic-
ipation. Indeed, the implementation of a public
daycare program oﬀered to poor families in Nic-
aragua led to a 14-percentage-point increase in
the likelihood that the mother would work.
Women place great value on flexibility, but it is a
luxury good. Because they are the main caregiv-
ers at home, women place great value on ﬂexible
================================
25
================================
Women place great value on flexibility, but it is a
luxury good. Because they are the main caregiv-
ers at home, women place great value on ﬂexible
work hours. A study conducted in Bogota looked
at women’s willingness to pay for that ﬂexibility. It
found that women were willing to earn a lower
monthly income in exchange for part-time work
or ﬂexible full-time work. However, the demand
for ﬂexible work hours seems to be driven by fac-
tors inﬂuencing the capacity to “pay” for a ﬂexi -
ble job, meaning that ﬂexibility is a luxury good,
accessible only to women with more household
income and higher levels of education. In contrast,
================================
26
================================
3
demand for part-time work is associated with the
limitations of the schedules of women looking for
a job. The ﬁndings suggest that policies aiming to
make work more ﬂexible in developing countries
could increase women’s labor force participation.
However, their impact may be limited among low -
er-income households.
The impact of social protection is unequal.  Social
programs can aﬀect women’s labor force participa-
tion. Non-labor income could disincentivize wom -
en’s participation in the labor market, and, when
that income comes from conditional cash transfers,
the time spent complying with the conditions may
reinforce such an eﬀect. The evidence from Latin
America and the Caribbean is not conclusive on
this point. For example, in Bolivia, the implemen -
================================
27
================================
reinforce such an eﬀect. The evidence from Latin
America and the Caribbean is not conclusive on
this point. For example, in Bolivia, the implemen -
tation of a cash transfer program with extensive
coverage, which is not focused on families with a
certain socioeconomic status and is conditional on
children attending schools, increased the labor force participation and employment of mothers by
nine percentage points while also increasing the number of hours worked by those already employed.
In Ecuador, in contrast, an unconditional cash transfer program focused on poor households produced
no changes in the medium term to women’s likelihood of working.
Women’s labor force participation rate is countercyclical. The economic cycle also plays a role in the
================================
28
================================
Women’s labor force participation rate is countercyclical. The economic cycle also plays a role in the
labor market participation of women. Although it is positively associated with economic growth in the